# Generated by Django 5.1.11 on 2025-08-03 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MineralType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MineralGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=100)),
                ('price_per_pound', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mineral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.mineraltype')),
            ],
            options={
                'verbose_name': 'Mineral Grade',
                'verbose_name_plural': 'Mineral Grades',
                'unique_together': {('mineral', 'grade_name')},
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_day_received', models.DateField(blank=True, null=True, verbose_name='Last Delivery Date')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_day_received', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='MineralTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_in_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Weight (kg)')),
                ('date_received', models.DateField(auto_now_add=True, verbose_name='Date Received')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Transaction Status')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mineralgrade')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('mineral_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mineraltype')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier')),
            ],
            options={
                'verbose_name': 'Mineral Transaction',
                'verbose_name_plural': 'Mineral Transactions',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='TransactionStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='core.mineraltransaction')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
