# Generated by Django 5.1.11 on 2025-08-04 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineraltransaction',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Received'),
        ),
        migrations.AlterField(
            model_name='mineraltransaction',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='core.mineralgrade'),
        ),
        migrations.AlterField(
            model_name='mineraltransaction',
            name='mineral_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral', to='core.mineraltype'),
        ),
        migrations.AlterField(
            model_name='mineraltransaction',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='core.supplier'),
        ),
    ]
