# Generated by Django 5.1.11 on 2025-08-06 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_supplier_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mineraltransaction',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='mineraltransaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid At'),
        ),
        migrations.AddField(
            model_name='mineraltransaction',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Paid By'),
        ),
        migrations.AddField(
            model_name='mineraltransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('opay', 'OPay'), ('moniepoint', 'Moniepoint'), ('palmpay', 'PalmPay'), ('cash', 'Cash'), ('other', 'Other Fintech')], max_length=20, null=True, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='mineraltransaction',
            name='payout_account_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Payout Account Name'),
        ),
        migrations.AddField(
            model_name='mineraltransaction',
            name='payout_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payout Account/Wallet Number'),
        ),
        migrations.AddField(
            model_name='mineraltransaction',
            name='payout_reference',
            field=models.TextField(blank=True, null=True, verbose_name='Payout Reference'),
        ),
    ]
