# Generated by Django 5.1.11 on 2025-08-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mineraltransaction_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineraltransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('opay', 'OPay'), ('moniepoint', 'Moniepoint'), ('palmpay', 'PalmPay'), ('kuda', 'Kuda'), ('flutterwave', 'Flutterwave'), ('paystack', 'Paystack'), ('cash', 'Cash'), ('other_fintech', 'Other Fintech'), ('access_bank', 'Access Bank'), ('gtbank', 'GTBank'), ('zenith_bank', 'Zenith Bank'), ('first_bank', 'First Bank'), ('uba', 'UBA'), ('fcmb', 'FCMB'), ('fidelity_bank', 'Fidelity Bank'), ('union_bank', 'Union Bank'), ('sterling_bank', 'Sterling Bank'), ('wema_bank', 'Wema Bank'), ('keystone_bank', 'Keystone Bank'), ('polaris_bank', 'Polaris Bank'), ('other_bank', 'Other Bank')], max_length=20, null=True, verbose_name='Payment Method'),
        ),
    ]
