# Generated by Django 5.1.11 on 2025-08-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mineraltransaction_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mineraltransaction',
            name='weight_in_kg',
        ),
        migrations.AddField(
            model_name='mineraltransaction',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=120, help_text='Enter the weight of the mineral received.', max_digits=10, verbose_name='Weight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mineraltransaction',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', help_text='Select the unit in which weight was measured.', max_length=2, verbose_name='Weight Unit'),
        ),
    ]
