# Generated by Django 5.1.11 on 2025-08-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_mineraltransaction_weight_in_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineraltransaction',
            name='agreed_payout',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, this amount will be used instead of calculated value (weight × price).', max_digits=12, null=True, verbose_name='Agreed Payout'),
        ),
    ]
