# Generated by Django 5.1.11 on 2025-08-13 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mineraltransaction_agreed_payout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MineralSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('quantity_unit', models.CharField(default='kg', max_length=10, verbose_name='Quantity Unit')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price per Unit')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Total Price')),
                ('buyer_name', models.CharField(max_length=150, verbose_name='Buyer Name')),
                ('buyer_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Buyer Contact')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Sale Date')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Sale Status')),
                ('reference_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Reference Number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='core.mineralgrade')),
                ('mineral_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.mineraltype')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mineral Sale',
                'verbose_name_plural': 'Mineral Sales',
                'ordering': ['-sale_date'],
            },
        ),
    ]
