# Generated by Django 5.1.11 on 2025-08-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mineralsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('expiry_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
