# Generated by Django 5.1.11 on 2025-08-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_license_expiry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'License', 'verbose_name_plural': 'Licenses'},
        ),
    ]
