# Generated by Django 5.1.11 on 2025-08-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_license_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineraltransaction',
            name='suppier_phone',
            field=models.CharField(blank=True, help_text='Optional: Phone number of the supplier for contact purposes.', max_length=20, null=True, verbose_name='Supplier Phone'),
        ),
    ]
