# Generated by Django 5.1.11 on 2025-08-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_mineraltransaction_suppier_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mineraltransaction',
            old_name='suppier_phone',
            new_name='supplier_phone',
        ),
    ]
