# Generated by Django 5.1.11 on 2025-08-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_suppier_phone_mineraltransaction_supplier_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineraltransaction',
            name='agreed_payout',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, this price per unit will be used instead of standard pricing (will be multiplied by weight).', max_digits=12, null=True, verbose_name='Negotiated Price Per Unit'),
        ),
    ]
