# Generated by Django 5.1.11 on 2025-08-28 07:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_mineraltransaction_agreed_payout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MineralBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('supplier_name', models.CharField(help_text='Name as provided at intake.', max_length=150, verbose_name='Supplier Name')),
                ('supplier_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Supplier Phone')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Received')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_batches', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_batches', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mineral_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mineral Batch',
                'verbose_name_plural': 'Mineral Batches',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MineralItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Weight')),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', max_length=2, verbose_name='Weight Unit')),
                ('agreed_payout', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides standard pricing if set.', max_digits=12, null=True, verbose_name='Negotiated Price Per Unit')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.mineralbatch')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mineralgrade')),
                ('mineral_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mineraltype')),
            ],
            options={
                'verbose_name': 'Mineral Item',
                'verbose_name_plural': 'Mineral Items',
            },
        ),
        migrations.CreateModel(
            name='PaymentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('opay', 'OPay'), ('moniepoint', 'Moniepoint'), ('palmpay', 'PalmPay'), ('kuda', 'Kuda'), ('flutterwave', 'Flutterwave'), ('paystack', 'Paystack'), ('cash', 'Cash'), ('other_fintech', 'Other Fintech'), ('access_bank', 'Access Bank'), ('gtbank', 'GTBank'), ('zenith_bank', 'Zenith Bank'), ('first_bank', 'First Bank'), ('uba', 'UBA'), ('fcmb', 'FCMB'), ('fidelity_bank', 'Fidelity Bank'), ('union_bank', 'Union Bank'), ('sterling_bank', 'Sterling Bank'), ('wema_bank', 'Wema Bank'), ('keystone_bank', 'Keystone Bank'), ('polaris_bank', 'Polaris Bank'), ('other_bank', 'Other Bank')], max_length=20, verbose_name='Payment Method')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('reference', models.TextField(blank=True, null=True, verbose_name='Reference')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.mineralbatch')),
            ],
            options={
                'verbose_name': 'Payment Component',
                'verbose_name_plural': 'Payment Components',
                'ordering': ['recorded_at'],
            },
        ),
    ]
