# Generated by Django 5.1.11 on 2025-08-27 21:23

from django.db import migrations, models
from django.db.models import Q

def create_mineralbatches_from_transactions(apps, schema_editor):
    MineralTransaction = apps.get_model('core', 'MineralTransaction')
    MineralBatch = apps.get_model('core', 'MineralBatch')
    Supplier = apps.get_model('core', 'Supplier')  # If still exists

    # Get all MineralTransactions
    transactions = MineralTransaction.objects.all().select_related(
        'supplier', 'recorded_by', 'approved_by', 'paid_by'
    )

    batches = []
    for tx in transactions:
        # Handle supplier
        supplier_name = tx.supplier.name if tx.supplier else tx.supplier_name

        batch = MineralBatch(
            # Reuse same ID to preserve FK references
            id=tx.id,

            # Batch number: MBYY-00001 format
            batch_no=f"MB{tx.date_received.strftime('%y')}-{str(tx.id).zfill(5)}",

            supplier_name=supplier_name,
            supplier_phone=tx.supplier_phone,
            recorded_by=tx.recorded_by,
            timestamp=tx.date_received,
            status=tx.status,
            approved_by=tx.approved_by,
            paid_at=tx.paid_at,
            paid_by=tx.paid_by,
            notes=getattr(tx, 'notes', None) or "Migrated from MineralTransaction"
        )
        batches.append(batch)

    # Bulk create (fast, but no signals)
    MineralBatch.objects.bulk_create(batches, ignore_conflicts=True)



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mineralbatch_mineralitem_paymentcomponent'),
    ]

    operations = [
         migrations.RunPython(create_mineralbatches_from_transactions, reverse_code=migrations.RunPython.noop),
    ]
