# Generated by Django 5.1.11 on 2025-08-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_transactionstatuslog_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='recorded_by',
        ),
        migrations.DeleteModel(
            name='MineralTransaction',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
