# Generated by Django 5.1.11 on 2025-08-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_supplier_recorded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcomponent',
            name='payout_account_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Payout Account Name'),
        ),
        migrations.AddField(
            model_name='paymentcomponent',
            name='payout_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payout Account/Wallet Number'),
        ),
    ]
