# Generated by Django 5.1.11 on 2025-08-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_paymentcomponent_payout_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineralsale',
            name='bvn',
            field=models.CharField(blank=True, help_text='Bank Verification Number', max_length=11, null=True, verbose_name='BVN'),
        ),
        migrations.AddField(
            model_name='mineralsale',
            name='driver_license',
            field=models.CharField(blank=True, help_text="Driver's license number", max_length=50, null=True, verbose_name="Driver's License"),
        ),
        migrations.AddField(
            model_name='mineralsale',
            name='international_id',
            field=models.CharField(blank=True, help_text='Passport or other international ID number', max_length=50, null=True, verbose_name='International ID'),
        ),
        migrations.AddField(
            model_name='mineralsale',
            name='nin',
            field=models.CharField(blank=True, help_text='National Identification Number', max_length=20, null=True, verbose_name='NIN'),
        ),
    ]
