# Generated by Django 5.1.11 on 2026-04-08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_mineralsale_bvn_mineralsale_driver_license_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mineralsale",
            name="sale_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Sale Date"),
        ),
    ]
