# core/utils/receipt_generator.py

import io
from django.http import FileResponse
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from datetime import datetime


def generate_receipt_pdf(html_string):
    """
    Generate PDF from HTML string (used by receipt_view).
    This is a simplified version. For production, consider WeasyPrint or xhtml2pdf.
    """
    # Since we're not using Django templates with ReportLab directly,
    # we'll create a basic PDF here.
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Header
    p.setFont("Helvetica-Bold", 16)
    p.drawString(50, height - 50, "Yarima Mining - Transaction Receipt")

    # Draw line
    p.setStrokeColor("#d6336c")
    p.setLineWidth(2)
    p.line(50, height - 60, width - 50, height - 60)

    # Reset color
    p.setFillColor("black")
    p.setFont("Helvetica", 10)

    # Note: In real use, parse HTML or pass structured data
    # This is a placeholder for actual receipt logic
    p.drawString(50, height - 80, "Receipt generated on: " + datetime.now().strftime('%Y-%m-%d %H:%M:%S'))

    p.drawString(50, height - 100, "See detailed receipt in system.")
    p.drawString(50, height - 120, "Batch processing enabled for multiple minerals.")

    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer


# Alternative: Full receipt generator (optional)
def generate_mineral_item_receipt(item, user):
    """
    Generate PDF receipt for a MineralItem (within a batch).
    """
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Header
    p.setFont("Helvetica-Bold", 16)
    p.setFillColor("#d6336c")
    p.drawString(50, height - 50, "Yarima Mining - Receipt")

    p.setFillColor("black")
    p.setFont("Helvetica", 10)
    p.drawString(50, height - 70, f"Batch No: {item.batch.batch_no}")
    p.drawString(50, height - 85, f"Date: {item.batch.timestamp.strftime('%Y-%m-%d %H:%M')}")
    p.drawString(50, height - 100, f"Generated by: {user.get_full_name() or user.username}")

    # Supplier
    p.setFont("Helvetica-Bold", 12)
    p.drawString(50, height - 130, "Supplier:")
    p.setFont("Helvetica", 11)
    p.drawString(50, height - 145, f"Name: {item.batch.supplier_name}")
    if item.batch.supplier_phone:
        p.drawString(50, height - 160, f"Phone: {item.batch.supplier_phone}")

    # Mineral Details
    p.setFont("Helvetica-Bold", 12)
    p.drawString(50, height - 190, "Mineral Details:")
    p.setFont("Helvetica", 11)
    y = height - 205
    for i, it in enumerate(item.batch.items.all()):
        p.drawString(50, y, f"{i+1}. {it.mineral_type.name} ({it.grade.grade_name})")
        p.drawString(250, y, f"{it.weight} {it.get_weight_unit_display()}")
        p.drawString(350, y, f"₦{it.total_value:,.2f}")
        y -= 18
        if y < 100:
            p.showPage()
            y = height - 50

    # Total
    p.setFont("Helvetica-Bold", 12)
    p.drawString(50, y - 20, f"Total Value: ₦{item.batch.total_value():,.2f}")

    # Footer
    p.setFont("Helvetica-Oblique", 9)
    p.setFillColor("#6b7280")
    p.drawString(50, 40, "Thank you for your business.")

    p.showPage()
    p.save()

    buffer.seek(0)
    filename = f"receipt_{item.batch.batch_no}.pdf"
    return FileResponse(buffer, as_attachment=False, filename=filename)