# Generated by Django 5.1.11 on 2025-08-15 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Serial Number')),
                ('expense_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('vendor_supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('pos', 'POS')], max_length=50, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('diesel_petrol', 'Diesel/Petrol'), ('generator', 'Generator'), ('truck', 'Truck'), ('cctv', 'CCTV'), ('air_condition', 'Air Condition'), ('electricity_spare_parts', 'Electricity Spare Parts'), ('company_machines', 'Company Machines'), ('commission', 'Commission'), ('laborers_workers', 'Laborer/Workers'), ('bore_hole', 'Bore Hole'), ('utility', 'Utility'), ('taxes_paid', 'Taxes Paid'), ('mosque', 'Mosque'), ('sadaq_donation', 'Sadaq/Donation'), ('medical_expenses', 'Medical Expenses'), ('miscellaneous', 'Miscellaneous')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='office4.invoice')),
            ],
        ),
    ]
