# Generated by Django 5.1.11 on 2025-08-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='category',
            field=models.CharField(choices=[('diesel_petrol', 'Diesel/Petrol'), ('generator', 'Generator'), ('truck', 'Truck'), ('cctv', 'CCTV'), ('air_condition', 'Air Condition'), ('electricity_spare_parts', 'Electricity Spare Parts'), ('company_machines', 'Company Machines'), ('commission', 'Commission'), ('laborers_workers', 'Laborer/Workers'), ('furniture', 'Furniture'), ('bore_hole', 'Bore Hole'), ('utility', 'Utility'), ('taxes_paid', 'Taxes Paid'), ('mosque', 'Mosque'), ('sadaq_donation', 'Sadaq/Donation'), ('medical_expenses', 'Medical Expenses'), ('miscellaneous', 'Miscellaneous')], max_length=50),
        ),
    ]
