# Generated by Django 5.1.11 on 2025-08-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('office_3', 'Office 3'), ('office_2', 'Office 2'), ('office_1', 'Office 1'), ('unassigned', 'Unassigned')], default='unassigned', help_text='User role, must be assigned by Super Admin or Office 3.', max_length=20),
        ),
    ]
